apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://gitlab.com/biletado/kustomize.git//overlays/kind?ref=main
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/dtag-it21/webeng2:sha-28678dd
    target:
      group: apps
      version: v1
      kind: Deployment
      name: assets
